### PR TITLE
WIP -- use develop branch of iiif, set up with iiif_testserver.cfg

### PR DESCRIPTION
**Pull request by zimeon**
@glenrobson I've made a number of changes in the `develop` branch of zimeon/iiif to try to improve the pretty sketchy handling different prefixes and to allow configuration. In particular, this PR adds a config file `iiif_testserver.cfg` which sets up the testserver to run just one PIL based, API v2.1 handler on http://localhost:8000/ but to return responses for being reverse proxied from http://iiif.io/api/image/2.1/example/reference/

In particular, access to something like http://localhost:8000/67352ccc-d1b0-11e1-89ae-279075081939/info.json will return:

```
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "http://iiif.io/api/image/2.1/example/reference/67352ccc-d1b0-11e1-89ae-279075081939",
  "height": 1000,
  "profile": [
    "http://iiif.io/api/image/2/level1.json",
    {
...
```

I'm sure there is more to do but I hope this is heading on the right path

### CODE REVIEW

**Comment by zimeon** [comment]
Oh, BTW, I assume that before we merge anything we'll want to get the iiif lib changes in `master` and change the Dockerfile back to pointing at `master`

**Comment by glenrobson** [comment]
Is it still possible to give access to the different versions of the API? At a minimum I would need 2.0 and 2.1 and ideally 1.1 and 1.0.

Thanks

Glen

**Comment by zimeon** [comment]
I can do that. We'll need enough config to specify a URI mapping for each different API handler. Maybe something like:

```
client_prefix_mapping=[ api/image/2.1/example/reference, 2.1_pil , api/image/2.0/example/reference, 2.0_pil  , etc.. ]
...
```

**Comment by glenrobson** [comment]
Ah good point, would a map be better than a list?
```
{
   "2.1" {
        BASE_URI="http://iiif.io/api/image/2.1/example/reference",
        path="2.1_pil"
   }
.. etc ..
}
```

**Comment by zimeon** [comment]
I don't think there is an easy way to do that without inventing a custom config file format

**Comment by zimeon** [comment]
I ended up refactoring the code and creating a specific wrapper `iiif_reference_server.py` -- it seemed that I was fighting general configuration to create something that worked for the reference server. Now, if you run it from command line or as WSGI it will create just PIL based services for 1.0, 1.1, 2.0 and 2.1 at the expected paths, e.g.

  * http://localhost:8000/api/image/2.1/example/reference
  * http://localhost:8000/api/image/2.0/example/reference

**Comment by glenrobson** [comment]
Tested the links from the IIIF/api website to the image reference implementation:

```
find ~/development/iiif/api/ -name "*.json" -exec grep 'api/image' {} \; |grep -v profile |grep reference |grep -o 'http://.*"'|sort |uniq|sed 's/"//g'
http://iiif.io/api/image/2.0/example/reference/detail
http://iiif.io/api/image/2.0/example/reference/detail/10,10,153,153/full/0/default.jpg
http://iiif.io/api/image/2.0/example/reference/detail/full/full/0/default.jpg
http://iiif.io/api/image/2.0/example/reference/detail/full/full/0/gray.jpg
http://iiif.io/api/image/2.0/example/reference/page1-full
http://iiif.io/api/image/2.0/example/reference/page1-full/100,100,1000,1600/full/0/default.jpg
http://iiif.io/api/image/2.0/example/reference/page1-full/full/full/0/default.jpg
http://iiif.io/api/image/2.0/example/reference/page1-full/full/full/0/gray.jpg
http://iiif.io/api/image/2.0/example/reference/page1-full/full/full/180/default.jpg
http://iiif.io/api/image/2.1/example/reference/detail
http://iiif.io/api/image/2.1/example/reference/detail/10,10,153,153/full/0/default.jpg
http://iiif.io/api/image/2.1/example/reference/detail/full/full/0/default.jpg
http://iiif.io/api/image/2.1/example/reference/detail/full/full/0/gray.jpg
http://iiif.io/api/image/2.1/example/reference/page1-full
http://iiif.io/api/image/2.1/example/reference/page1-full/100,100,1000,1600/full/0/default.jpg
http://iiif.io/api/image/2.1/example/reference/page1-full/full/full/0/default.jpg
http://iiif.io/api/image/2.1/example/reference/page1-full/full/full/0/gray.jpg
http://iiif.io/api/image/2.1/example/reference/page1-full/full/full/180/default.jpg
```

and all looks OK. Merging now and will monitor to see if the live version is updated.

**Pull request merged**
